### ISSUE TITLE
1.4.5-SNAPSHOT library

### ISSUE THREAD

**Issue by walternate** [tuxBurner/play-neo4jplugin#19]
Been trying to get going with this for some testing but the 1.4.5-SNAPSHOT dependency is not available. I guess I can revert down to 1.4.4 but I would like to test with Play 2.4 and see that there is some examples coming together, e.g. from Carlos Moro. Thanks.

**Comment by tuxBurner** [comment]
@walternate hi sorry for the late reply, was quite busy the last time :) So now i have vacations and will start migrating the hole plugin
