### ISSUE TITLE
spring-data-neo4j and spring-data-neo4j-rest  upgraded from 3.4.0.RC1 to 3.4.0.RELEASE

### ISSUE THREAD

**Issue by DwayneSmurdon** [tuxBurner/play-neo4jplugin#21]
The RC1 artifacts could not be found.  I updated the build.sbt file and submitted a pull request.  This is my first ever contribution to a github project, so if I made a mistake, please let me know.

I also commented out the local maven repository line, as this caused a "uri has an authority component" error.  I think this is likely a windows related issue.  But, if someone doesn't have a local maven repository at all, this may also fail, I believe.  Either way, I commented it out, but added a comment about it.

This article discusses the "uri has an authority component" error.  http://stackoverflow.com/questions/30624099/sbt-0-13-8-uri-has-an-authority-component

So happy to see this project/template.

**Comment by tuxBurner** [comment]
Done with  your pr :)
