### ISSUE TITLE
Add support for SDN 4.0.0

### ISSUE THREAD

**Issue by patxiperpetuall** [tuxBurner/play-neo4jplugin#22]
Hi @tuxBurner,

I would appreciate a lot if you could update the plugin to support Spring Data Neo4j 4.0.0

I am apparently having some issues with current SDN.

Thanks for your work :)

**Comment by DwayneSmurdon** [comment]
Hah.  I just came here to open the same issue.  I hadn't realized this wasn't using the latest version of SDN. I had been reading the SDN 4.0 documentation and some of it didn't work.

I may play with switching out SDN 3.4 with SDN 4.0.

SDN 4.0, it seems, can be quite a bit different that earlier version, with some functionality being removed.  So, it's possible that it might be better to fork and have two versions of this plugin.  One working with SDN 3.4 (and perhaps anything up to but not including 4.0) and another with SDN 4.0 and beyond.

**Comment by tuxBurner** [comment]
Hi guys,

  i will start working on this

**Comment by nayish** [comment]
Hi,

Can you open a branch and put your partial code for SDN 4 so maybe others can help with pull requests?

thanks, Nahchson

**Comment by DwayneSmurdon** [comment]
Sounds great.  I agree with Nahchson, if you post, perhaps we can help. :)

**Comment by amitsz** [comment]
There is update of the plugin? i'm waiting for it.

**Comment by nitz70** [comment]
Hey, when an update is coming out to the plugin? I need it fast...

**Comment by tuxBurner** [comment]
Hi guys sorry for the late response :)
I am at vacations @ the moment. Tomorrow i am coming home :)

**Comment by DwayneSmurdon** [comment]
I don't recall us approving your vacation time. ;)

**Comment by tuxBurner** [comment]
Hi started the work in the branch sdn4.0 :) 
Lots of changes there but looking forward.

**Comment by DwayneSmurdon** [comment]
Any update on this? :)  I started a port and had to make a ton of changes and then I got into a state that won't run at all. Now my current version with SDN 3.4 is broken, too.   I really wish I had pushed some code along the way, but I didn't.  I'm about to download and start over.

**Comment by DwayneSmurdon** [comment]
Hey @tuxBurner!  Just checking in to see if there's any more progress here.  Does the sdn4.0 branch work?  I'm going to be starting a new project soon, so I'm hoping to base it on sdn4.0. :)

**Comment by unterstein** [comment]
Hi all,

SDN 4.0 was not able to start in play, because of some strange classloading issues in SDN and OGM. @tuxBurner and me was involved to solve this issues for SDN 4.1, see https://jira.spring.io/browse/DATAGRAPH-830 and https://github.com/spring-projects/spring-data-neo4j/issues/315.

I am starting to integrate SDN 4.1 (currently only snapshot) this evening and if you like, we will contribute a SNAPSHOT release. Is this ok für you?

Cheers Johannes

**Comment by DwayneSmurdon** [comment]
Happy 2016!

In an effort to spend more time reading your emails and less time organizing spam, I've changed my email address.  It is now: =dsmurdon at predictable data dot com=; without spaces, equal signs or the word 'at', of course.

If you are a human, please resend your email to my new address. If somehow this email responds to a list or group, please do not add this add or change my address.  If you notice that I'm unintentionally spamming a list with this autoresponder, please contact me at the new address immediately. 

I apologize for the inconvenience and appreciate your help.  I look forward to reading your email.

Sincerely,

-Dwayne

**Comment by DwayneSmurdon** [comment]
Yes @unterstein, please do a snapshot.  If I have time this weekend, I'll see how it works for me and report back. Thank you for working on this, Johannes. 


-Dwayne

**Comment by tuxBurner** [comment]
Hi thaaaaanks a lot to @unterstein :)

@DwayneSmurdon i released a Snapshot 1.5.1 in my repo you can test :)

**Comment by DwayneSmurdon** [comment]
@tuxBurner - I bet you're glad to be able to close this one. I'll try to do some testing, soon.
